### ISSUE TITLE
Loading and interpreting less files in the browser with a plugin

### ISSUE THREAD

**Issue by smac89** [systemjs/systemjs#1691]
What are the steps for accomplishing this? So far I have done:

`npm i --save-dev systemjs-plugin-css systemjs-plugin-less less`

Then in my `systemjs.config.ts`, I have:
```js
meta: {
    '*.less': {
        loader: 'less'
    }
},

map: {
    less: 'npm:systemjs-plugin-less'
}
```
What I expected this to do is to transpile the less files into css when I load a page that requires less. However, when I load the page, my browser still gets the less file and I see things like:

```less
.wrapper[_ngcontent-c0] {
    width: 420px;
    margin: @auto; // <-- This should have been changed right?
    background: url(/assets/images/dark-wall.png);
}
```

What should I do to make it work? Am I right to assume that the plugin is supposed to have compiled the less file to css or am I missing something?

## Note: This is angular2 app and I am loading the less file as a style for a component
